server:
  port: 8200

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: brog
      auto-index-creation: true
  datasource:
    url: jdbc:mysql://localhost:3306/brog_db
    username: root
    password: 123 # Vacant for privacy issue (should be completed when running)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.163.com
    username: 123 # Vacant for privacy protection (should be completed when running)
    password: 123 # Vacant for privacy protection (should be completed when running)
    port: 465
    default-encoding: UTF-8
    protocol: smtps
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

material:
  rootpath: /home/ # Vacant for privacy issue (should be completed when running)